// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjjbhtchuihrwesmnxlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqamJodGNodWlocndlc21ueGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzU1NTQsImV4cCI6MjA2MDIxMTU1NH0.fUZWPh-9Ka5La4jIAzgL_Voiw79QxfQFedmlJog3uR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);